// High-fidelity Multi-Source Music Catalog for India & International Songs

export const MUSIC_SOURCES = [
  { id: 'all', name: 'All Sources', icon: 'fa-globe', desc: 'Aggregated Global & Desi Catalog' },
  { id: 'india', name: 'India Hits', icon: 'fa-flag', desc: 'Bollywood, Punjabi & Desi Top Charts' },
  { id: 'international', name: 'International', icon: 'fa-earth-americas', desc: 'Billboard Top 50 & Global Pop' },
  { id: 'punjabi', name: 'Punjabi Beats', icon: 'fa-drum', desc: 'Karan Aujla, Diljit, Sidhu, AP Dhillon' },
  { id: 'bollywood', name: 'Bollywood Romance', icon: 'fa-film', desc: 'Arijit Singh, Pritam, Shreya Ghoshal' },
  { id: 'lofi', name: 'Lofi & Chill', icon: 'fa-mug-hot', desc: 'Peaceful acoustic & bedroom pop' },
];

export const INDIA_TOP_TRACKS = [
  {
    id: 'tYqZK7bq5Bs',
    title: 'Ku Ku',
    artist: 'Bilal Saeed',
    plays: '134M',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'tYqZK7bq5Bs',
    duration: '3:28',
    durationSec: 208,
    source: 'india',
    sourceLabel: '🇮🇳 India Hits',
    genre: 'Punjabi Pop',
  },
  {
    id: 'dZ0fwJojhrs',
    title: 'Lahore',
    artist: 'Guru Randhawa',
    plays: '1.2B',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'dZ0fwJojhrs',
    duration: '3:15',
    durationSec: 195,
    source: 'india',
    sourceLabel: '🇮🇳 India Hits',
    genre: 'Punjabi Dance',
  },
  {
    id: 'V1Pl8CzNzCw',
    title: 'Tauba Tauba (Bad Newz)',
    artist: 'Karan Aujla',
    plays: '280M',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'V1Pl8CzNzCw',
    duration: '3:26',
    durationSec: 206,
    source: 'india',
    sourceLabel: '🇮🇳 India Trending',
    genre: 'Desi Hip-Hop',
  },
  {
    id: '_deqdZmKzyg',
    title: 'Zaalima',
    artist: 'Arijit Singh & Harshdeep Kaur',
    plays: '1.1B',
    coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: '_deqdZmKzyg',
    duration: '4:59',
    durationSec: 299,
    source: 'india',
    sourceLabel: '🇮🇳 Bollywood',
    genre: 'Bollywood Romantic',
  },
  {
    id: 'BddP6PY42yo',
    title: 'Kesariya (Brahmāstra)',
    artist: 'Arijit Singh & Pritam',
    plays: '620M',
    coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'BddP6PY42yo',
    duration: '4:28',
    durationSec: 268,
    source: 'india',
    sourceLabel: '🇮🇳 Bollywood',
    genre: 'Romantic',
  },
  {
    id: 'f02mOEt11OQ',
    title: 'Ishq Tera',
    artist: 'Guru Randhawa',
    plays: '560M',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'f02mOEt11OQ',
    duration: '3:32',
    durationSec: 212,
    source: 'india',
    sourceLabel: '🇮🇳 India Hits',
    genre: 'Romantic Pop',
  },
  {
    id: 'usvVGXFIpTM',
    title: 'Casa Tupka Anthemo',
    artist: 'Yo Yo Honey Singh',
    plays: '82M',
    coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'usvVGXFIpTM',
    duration: '3:45',
    durationSec: 225,
    source: 'india',
    sourceLabel: '🇮🇳 Desi Pop',
    genre: 'Desi Rap',
  },
  {
    id: 'Kh49Zqa84IE',
    title: 'Pata Chalgea',
    artist: 'Imran Khan',
    plays: '335M',
    coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'Kh49Zqa84IE',
    duration: '3:20',
    durationSec: 200,
    source: 'india',
    sourceLabel: '🇮🇳 Urban Desi',
    genre: 'Urban Punjabi',
  },
  {
    id: 'cl0a3i2wFcc',
    title: 'G.O.A.T.',
    artist: 'Diljit Dosanjh',
    plays: '340M',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'cl0a3i2wFcc',
    duration: '3:43',
    durationSec: 223,
    source: 'india',
    sourceLabel: '🇮🇳 Punjabi Top',
    genre: 'Punjabi Hip-Hop',
  },
  {
    id: 'n_FCrCQ6-9U',
    title: '295',
    artist: 'Sidhu Moosewala',
    plays: '590M',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'n_FCrCQ6-9U',
    duration: '4:30',
    durationSec: 270,
    source: 'india',
    sourceLabel: '🇮🇳 Punjabi Top',
    genre: 'Punjabi Rap',
  },
  {
    id: 'Hu5l420BreY',
    title: 'Husn',
    artist: 'Anuv Jain',
    plays: '190M',
    coverUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'Hu5l420BreY',
    duration: '3:38',
    durationSec: 218,
    source: 'india',
    sourceLabel: '🇮🇳 Indie India',
    genre: 'Acoustic Indie',
  },
  {
    id: 'k4yXQkGIf5M',
    title: 'With You',
    artist: 'AP Dhillon',
    plays: '145M',
    coverUrl: 'https://images.unsplash.com/photo-1520523839898-507127042a9b?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'k4yXQkGIf5M',
    duration: '2:34',
    durationSec: 154,
    source: 'india',
    sourceLabel: '🇮🇳 India Hits',
    genre: 'Punjabi R&B',
  },
];

export const INTERNATIONAL_TOP_TRACKS = [
  {
    id: '4NRXx6U8ABQ',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    plays: '4.2B',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: '4NRXx6U8ABQ',
    duration: '3:20',
    durationSec: 200,
    source: 'international',
    sourceLabel: '🌍 Global Top 50',
    genre: 'Synthpop',
  },
  {
    id: 'ic8j13piAhQ',
    title: 'Cruel Summer',
    artist: 'Taylor Swift',
    plays: '2.4B',
    coverUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'ic8j13piAhQ',
    duration: '2:58',
    durationSec: 178,
    source: 'international',
    sourceLabel: '🌍 Billboard Hot 100',
    genre: 'Pop',
  },
  {
    id: 'd5gf9dXbPi0',
    title: 'Birds of a Feather',
    artist: 'Billie Eilish',
    plays: '1.2B',
    coverUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'd5gf9dXbPi0',
    duration: '3:16',
    durationSec: 196,
    source: 'international',
    sourceLabel: '🌍 Global Top 50',
    genre: 'Indie Pop',
  },
  {
    id: 'kPa7bsKwL-c',
    title: 'Die With A Smile',
    artist: 'Lady Gaga & Bruno Mars',
    plays: '850M',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'kPa7bsKwL-c',
    duration: '4:11',
    durationSec: 251,
    source: 'international',
    sourceLabel: '🌍 Billboard Hot 100',
    genre: 'Pop Soul',
  },
  {
    id: 'eVli-tstM5E',
    title: 'Espresso',
    artist: 'Sabrina Carpenter',
    plays: '1.4B',
    coverUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'eVli-tstM5E',
    duration: '2:55',
    durationSec: 175,
    source: 'international',
    sourceLabel: '🌍 Global Viral',
    genre: 'Dance-Pop',
  },
  {
    id: '34Na4j8AVgA',
    title: 'Starboy (feat. Daft Punk)',
    artist: 'The Weeknd',
    plays: '3.1B',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: '34Na4j8AVgA',
    duration: '3:50',
    durationSec: 230,
    source: 'international',
    sourceLabel: '🌍 Global Top 50',
    genre: 'R&B / Electro',
  },
  {
    id: 'kTJczUoc26U',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    plays: '2.8B',
    coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'kTJczUoc26U',
    duration: '2:21',
    durationSec: 141,
    source: 'international',
    sourceLabel: '🌍 Billboard Hot 100',
    genre: 'Pop Rap',
  },
  {
    id: 'TUVcZfQe-Kw',
    title: 'Levitating',
    artist: 'Dua Lipa',
    plays: '2.1B',
    coverUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'TUVcZfQe-Kw',
    duration: '3:23',
    durationSec: 203,
    source: 'international',
    sourceLabel: '🌍 Global Top 50',
    genre: 'Nu-Disco',
  },
  {
    id: 'H5v3kku4y6Q',
    title: 'As It Was',
    artist: 'Harry Styles',
    plays: '3.3B',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'H5v3kku4y6Q',
    duration: '2:47',
    durationSec: 167,
    source: 'international',
    sourceLabel: '🌍 Global Top 50',
    genre: 'Synthpop',
  },
  {
    id: 'ApXoWvfEYVU',
    title: 'Sunflower',
    artist: 'Post Malone & Swae Lee',
    plays: '3.6B',
    coverUrl: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'ApXoWvfEYVU',
    duration: '2:38',
    durationSec: 158,
    source: 'international',
    sourceLabel: '🌍 Billboard Hot 100',
    genre: 'Hip-Hop / Pop',
  },
  {
    id: 'JGwWNGJdvx8',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    plays: '6.1B',
    coverUrl: 'https://images.unsplash.com/photo-1520523839898-507127042a9b?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: 'JGwWNGJdvx8',
    duration: '3:53',
    durationSec: 233,
    source: 'international',
    sourceLabel: '🌍 All-Time Global Hit',
    genre: 'Pop',
  },
  {
    id: '7wtfhZwyrcc',
    title: 'Believer',
    artist: 'Imagine Dragons',
    plays: '2.6B',
    coverUrl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&q=80&w=400&h=400',
    audioId: '7wtfhZwyrcc',
    duration: '3:24',
    durationSec: 204,
    source: 'international',
    sourceLabel: '🌍 Global Rock/Pop',
    genre: 'Alt-Rock',
  },
];

export const ALL_MUSIC_CATALOG = [
  ...INDIA_TOP_TRACKS,
  ...INTERNATIONAL_TOP_TRACKS,
];

export function getSongsBySource(sourceId = 'all') {
  if (sourceId === 'india') return INDIA_TOP_TRACKS;
  if (sourceId === 'international') return INTERNATIONAL_TOP_TRACKS;
  if (sourceId === 'punjabi') return INDIA_TOP_TRACKS.filter((s) => s.genre?.includes('Punjabi') || s.artist.includes('Karan') || s.artist.includes('Diljit') || s.artist.includes('Guru') || s.artist.includes('Sidhu') || s.artist.includes('AP'));
  if (sourceId === 'bollywood') return INDIA_TOP_TRACKS.filter((s) => s.genre?.includes('Bollywood') || s.genre?.includes('Romantic') || s.artist.includes('Arijit') || s.artist.includes('Pritam'));
  if (sourceId === 'lofi') return ALL_MUSIC_CATALOG.filter((s) => s.genre?.includes('Acoustic') || s.genre?.includes('Indie') || s.genre?.includes('Pop Soul'));
  return ALL_MUSIC_CATALOG;
}
